feature/articles-organism done
WS-Jedp/NeoBit pull request #19
Opened 2020-07-13 05:26 UTC by WS-Jedp

2020-07-13 20:26 UTC, abdieljortega commented on src/styles/components/molecules/Article.scss
> +    width: 80%;
```suggestion
    width: 80%;
```

This is not necesary

2020-07-13 20:34 UTC, onlyabdiel requested changes
You shouldn't leave this like this.

The articles should look to the center

![image](https://user-images.githubusercontent.com/38680546/87350895-280f3f00-c51e-11ea-90c3-4155eb86e247.png)

2020-07-14 16:21 UTC, WS-Jedp commented
POsition of the articles fixed

2020-07-14 21:24 UTC, onlyabdiel approved these changes

2020-07-14 21:24 UTC, merged